source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'

gem 'rake'

group :development, :test do
  gem 'pry'
  gem 'pry-nav'
  gem 'pry-remote'
  gem 'rack-test'
end

group :test do
  gem 'codeclimate-test-reporter', require: nil
  gem 'rspec'
end